name: Build and Publish Docker Image

on:
  pull_request:
    types: [closed]  
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


     - name: print secrets
  run: |
      echo $DEV_ENV_FILE src/.env
      cat src/.env
  shell: bash
  env:
    DEV_ENV_FILE : ${{secrets.PRODUCTION}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/politecnianos/montenegro-mlikota-galvan-ibarrola-back/my-app:latest ./Back
      - name: Push the Docker image
        run: |
          docker push ghcr.io/politecnianos/montenegro-mlikota-galvan-ibarrola-back/my-app:latest
